// Auto-generated by ECC GAS IDE — pushes the repo's GAS files back into the
// Apps Script project on every push, using the GAS_CREDS / GAS_SCRIPT_ID secrets.
import { google } from 'googleapis'
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

const creds = JSON.parse(process.env.GAS_CREDS)
const scriptId = process.env.GAS_SCRIPT_ID
const oauth = new google.auth.OAuth2(creds.client_id, creds.client_secret)
oauth.setCredentials({ refresh_token: creds.refresh_token })
const script = google.script({ version: 'v1', auth: oauth })

const files = []
function walk(dir, prefix) {
  for (const entry of readdirSync(dir)) {
    if (entry === '.git' || entry === '.github' || entry === 'node_modules') continue
    const full = join(dir, entry)
    const rel = prefix ? prefix + '/' + entry : entry
    if (statSync(full).isDirectory()) { walk(full, rel); continue }
    if (rel.endsWith('.gs')) files.push({ name: rel.slice(0, -3), type: 'SERVER_JS', source: readFileSync(full, 'utf8') })
    else if (rel.endsWith('.html')) files.push({ name: rel.slice(0, -5), type: 'HTML', source: readFileSync(full, 'utf8') })
    else if (rel === 'appsscript.json') files.push({ name: 'appsscript', type: 'JSON', source: readFileSync(full, 'utf8') })
  }
}
walk('.', '')

await script.projects.updateContent({ scriptId, requestBody: { files } })
console.log('Deployed ' + files.length + ' files to ' + scriptId)
